### PR TITLE
Fix position error

### PR DESCRIPTION
**Pull request by edomato**
This PR fixes an error in the readBytes method when the while loop ends which adds 1 to the position leaving 1 more position beyond the length.

This makes the DataWrapper eats one more byte from the buffer when this method is used which is wrong :disappointed: 

Ernesto

### CODE REVIEW

**Comment by edomato** [comment]
The second commit just makes the method to return an explicit Address object.

On the SMPP specification, the address has three separated values which are not tightly related, so this changes make the method return an Address object even when the length of the third field (value here and address_range in the specification) is 0.

Ernesto

**Comment by edomato** [comment]
The last commit, as the messages says, implements the TLV optional values through a PHP trait.

Sorry if this pull request is a little mess, but I don't know (yet) how to make separate PRs on Github :disappointed: 

Ernesto

**Comment by alexeevdv** [comment]
Hey @edomato, thank your for contribution.
To make separate pull requests you need to create separate branch for each change. Then you create pull request for each of these branches. F.e. your current pull request is made from master branch

**Comment by edomato** [comment]
> Hey @edomato, thank your for contribution.
> To make separate pull requests you need to create separate branch for each change. Then you create pull request for each of these branches. F.e. your current pull request is made from master branch

Oh, perfect, I got it, so I need to create topic branches with every change :smile: 

So, do you want me to close this PR and create three different ones?.

Greets.
Ernesto

**Comment by alexeevdv** [comment]
Thanks, i've adopted your changes regarding to the DataWrapper. Can not adopt TLV changes since they are implemented using traits. I will find a way to implement it in other way

**Comment by edomato** [comment]
> Thanks, i've adopted your changes regarding to the DataWrapper. Can not adopt TLV changes since they are implemented using traits. I will find a way to implement it in other way

Ok, no problem. Just to be curious, why you don't like the Traits implementation? :smile: 

I'll see another way to do it and let you know about it :wink: 

I'm closing this PR since it even has conflicts and you already applied to other 2 commits somehow.

Greets.
Ernesto

**Comment by alexeevdv** [comment]
https://eliasvo.wordpress.com/2015/06/07/php-traits-if-they-werent-evil-theyd-be-funny/

**Pull request closed without merging**
